---
.travis.yml:
  script: "\"bundle exec rake validate lint spec SPEC_OPTS='--format documentation'\""
  includes:
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
Gemfile:
  required:
    ':development, :unit_tests':
      - gem: json
      - gem: metadata-json-lint
      - gem: puppet_facts
      - gem: puppet-blacksmith
      - gem: puppetlabs_spec_helper
      - gem: rspec-core
      - gem: simplecov
    ':system_tests':
      - gem: beaker-puppet_install_helper
      - gem: beaker-rspec
      - gem: master_manipulator
      - gem: serverspec
Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_80chars'
  - 'disable_class_inherits_from_params_class'
  - 'disable_documentation'
  - 'disable_single_quote_string_with_variables'
