---
.travis.yml:
  script: "\"bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'\""
  includes:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
Gemfile:
  supports_windows: false
  required:
    ':development':
      - gem: rake
      - gem: rspec
        version: '~>3.0.0'
      - gem: puppet-lint
      - gem: puppetlabs_spec_helper
        version: '~>0.10.3'
      - gem: puppet_facts
      - gem: mocha
        version: '~>0.10.5'
      - gem: pry
      - gem: pry-stack_explorer
      - gem: pry-byebug
        condition: "RUBY_VERSION >= '2.0'"
      - gem: pry-debugger
        condition: "RUBY_VERSION < '2.0'"
    ':system_tests':
      - gem: beaker-rspec
      - gem: beaker
      - gem: beaker-puppet_install_helper
appveyor.yml:
  appveyor_bundle_install: "bundle install --jobs 4 --retry 2 --without system_tests"
  matrix:
    - PUPPET_GEM_VERSION: '~> 3.0'
      RUBY_VER: 193
    - PUPPET_GEM_VERSION: '~> 3.0'
      RUBY_VER: 200-x64
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 21
    - PUPPET_GEM_VERSION: '~> 4.0'
      RUBY_VER: 21-x64
  test_script:
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_80chars'
  - 'disable_class_inherits_from_params_class'
  - 'disable_documentation'
  - 'disable_single_quote_string_with_variables'
