---
sudo: false
language: ruby
bundler_args: --without system_tests
script: <%= @configs['script'] %>
matrix:
  fast_finish: true
  include:
<% @configs['includes'].each do |include| -%>
  - rvm: <%= include['rvm'] %>
    env: <%= include['env'] %>
<% end -%>
<% if @configs['extras'] -%>
<%   @configs['extras'].each do |extra| -%>
  - rvm: <%= extra['rvm'] %>
    env: <%= extra['env'] %>
<%   end -%>
<% end -%>
  allow_falures:
    - rvm: 2.1.5
      env: PUPPET_GEM_VERSION="~> 4.0"
notifications:
  email: false
